# Generated by Django 2.1.7 on 2024-04-17 06:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20240414_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='useremail',
            field=models.EmailField(default=django.utils.timezone.now, max_length=128, verbose_name='사용자 이메일'),
            preserve_default=False,
        ),
    ]
